// DO NOT EDIT THIS FILE
// CS0455 Fall 2022
// Assignment 1 Test file
// Compile Length.java, then compile and run this file
// Check the output is as expected



public class LengthTest {
	
	public static void main(String[] args) {
	
		Length len1, len2, len3;
		len1 = new Length();
		len1.setMeters(1345);
		len1.setCentimeters(89);
		len2 = new Length();
		len3 = new Length(0, 34);
		
		System.out.println("Lengths are");
		System.out.println(len1 + "\n" + len2 + "\n" + len3 + "\n");
			
		System.out.println("len1 is zero? " + len1.isLengthZero());
		System.out.println("len2 is zero? " + len2.isLengthZero());
		System.out.println("len3 is zero? " + len3.isLengthZero()+ "\n");
		
		System.out.println("Meters in len1 is " + len1.getMeters());
		System.out.println("Centimeters in len1 is " + len1.getCentimeters() + "\n");

		System.out.println("Lengths as total number of centimeters are");
		System.out.println(len1.totalCentimeters() + "  " + len2.totalCentimeters() 
											+ "  " + len3.totalCentimeters() + "\n");
			
		System.out.println("In meters the lengths are");
		System.out.println(len1.totalMeters() + "  " + len2.totalMeters() + "  " + len3.totalMeters() + "\n");

		
		
	}
}
		
