--Table Creation--

DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Car;
DROP TABLE IF EXISTS Technician;
DROP TABLE IF EXISTS Estimate;
DROP TABLE IF EXISTS Job;
DROP TABLE IF EXISTS Repair;
DROP TABLE IF EXISTS Part;
DROP TABLE IF EXISTS Repair_Job;

CREATE TABLE Customer (
custID INT(10) NOT NULL AUTO_INCREMENT, 
firstName VARCHAR(50) NOT NULL,
firstName VARCHAR(50) NOT NULL, 
address VARCHAR(50), 
phone VARCHAR(20),
);
--CONSTRAINT Customer_custID_pk PRIMARY KEY (custID)

CREATE TABLE Car (
carID INT(10) NOT NULL AUTO_INCREMENT,
make VARCHAR(50) NOT NULL,
model VARCHAR(50) NOT NULL,
plate VARCHAR(10) NOT NULL,
year INT(4),
custID INT(10) NOT NULL
);
--CONSTRAINT Car_carID_pk PRIMARY KEY (carID),
--CONSTRAINT Car_custID_fk FOREIGN KEY(custID) REFERENCES Customer(custID) ON DELETE SET NULL

CREATE TABLE Technician (
techID INT(10) NOT NULL AUTO_INCREMENT,
firstName VARCHAR(50) NOT NULL,
lastName VARCHAR(50) NOT NULL,
wage INT(10)
);
--CONSTRAINT Technician_techID_pk PRIMARY KEY (techID)

CREATE TABLE Estimate (
estID INT(10) NOT NULL AUTO_INCREMENT,
estCost INT(50) NOT NULL,
estDate DATE,
techID INT(10) NOT NULL,
carID INT(10) NOT NULL
);
--CONSTRAINT Estimate_estID_pk PRIMARY KEY (estID),
--CONSTRAINT Estimate_techID_fk FOREIGN KEY(techID) REFERENCES Technician(techID) ON DELETE SET NULL,
--CONSTRAINT Estimate_carID_fk FOREIGN KEY(carID) REFERENCES Car(carID) ON DELETE SET NULL

CREATE TABLE Job (
jobID INT(10) NOT NULL AUTO_INCREMENT,
jobDate DATE,
completion DATE,
carID INT(10) NOT NULL,
techID INT(10) NOT NULL,
estID INT(10) NOT NULL
);
--CONSTRAINT Job_jobID_pk PRIMARY KEY (jobID),
--CONSTRAINT Job_carID_fk FOREIGN KEY(carID) REFERENCES Car(carID) ON DELETE SET NULL,
--CONSTRAINT Job_techID_fk FOREIGN KEY(techID) REFERENCES Technician(techID) ON DELETE SET NULL,
--CONSTRAINT Job_estID_fk FOREIGN KEY(estID) REFERENCES Estimate(estID) ON DELETE SET NULL

CREATE TABLE Repair (
repID INT(10) NOT NULL AUTO_INCREMENT,
description VARCHAR(100),
time INT(10),
repCost INT(10)
);
--CONSTRAINT Repair_repID_pk PRIMARY KEY (repID)

CREATE TABLE Part (
partID INT(10) NOT NULL AUTO_INCREMENT,
repairID INT(10) NOT NULL
);
--CONSTRAINT Part_partID_pk PRIMARY KEY (partID),
--CONSTRAINT Part_repairID_fk FOREIGN KEY(repairID) REFERENCES Repair(repID) ON DELETE SET NULL

CREATE TABLE Repair_Job (
repID INT(50) NOT NULL,
jobID INT(50) NOT NULL
);
--CONSTRAINT Repair_Job_repID_jobID_pk PRIMARY KEY (repID, jobID),
--CONSTRAINT Repair_Job_repID_fk FOREIGN KEY(repID) REFERENCES Repair(repID) ON DELETE SET CASCADE,
--CONSTRAINT Repair_Job_jobID_fk FOREIGN KEY(jobID) REFERENCES Job(jobID) ON DELETE SET CASCADE

--Table Insertion--

INSERT INTO Customer VALUES(1, 'Joey', 'Boey', '150 Silly St', '814242555');
INSERT INTO Car VALUES(1, 'Elantra', 'Hyundai', 'ABCEDF', 2024, 1);
INSERT INTO Technician VALUES(1, 'John', 'Colt', 25000);
INSERT INTO Estimate VALUES(1, 5000, '2024-04-11', 1, 1);
INSERT INTO Job VALUES(1, '2024-04-11', '2024-05-19', 1, 1, 1);
INSERT INTO Repair VALUES(1, 'dummy description', 5, 10);
INSERT INTO Part VALUES(1, 1);
INSERT INTO Repair_Job VALUES(1, 1);